### ISSUE TITLE
Set up project and start exercise A

### ISSUE THREAD

**Issue by francoiscrouzet** [Zfitmeta/Mentoring#1]
# presentation 

This project will contains different directories, one for each exercise. They will be independant.   
  
Exercise A would be a basic static html page without templating, but will allow us to get used to the work organization.  

# setup

## gitflow

- read https://nvie.com/posts/a-successful-git-branching-model/ If it’s too complicated or irrelevant , search for a simplified explanation of gitflow
- Discuss with Francois about it
- Create the branch develop from branch main
- Create a branch from develop, for this issue. It should be named:` #1-set-up-project-and-start-exercise-A`

## naming and git

- branches should be named `#<issue number>-<name-of-the-issue>`
- PRs (pull requests) should be named like branches
- Commit naming should follow this convention https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53 + always prefix the name with the issue number. For instance :` #1 Display basic informations on user page`
- Use atomic commits

# Exercise

- create the directory Exercise-A-Static-page
- Create a user.html file
- Put in it some text like :
Id: 1    
Forename Sarah   
Name: ….    
Adress: ….   
Etc.    

- once finished, commit the result
- Then push the branch
- You should be able to create a pull request and assign it to me

**Comment by Sarahyoussef19** [comment]
https://github.com/Zfitmeta/Mentoring/pull/4
