### ISSUE TITLE
Add bootstrap to the project and use it

### ISSUE THREAD

**Issue by francoiscrouzet** [Zfitmeta/Mentoring#3]
- create a branch (as always: from develop, and named as usual)
- add bootstrap to the user.html file
- remark how the design, font, margin etc differs with and without bootstrap
- Put your user infos inside a bootstrap panel (or is it named a card?)
- Optional: add a css file, and tweak the display, getting inspiration from the book “refactoring ui”
- Commit  (several time, with atomic commits : one commit per small tasks)
- Push and create a PR, assign it to me
- Make a screenshot of the results, and add the screenshot as a comment in this issue

**Comment by Sarahyoussef19** [comment]
<img width="1280" alt="Screenshot 2022-05-17 at 09 14 57" src="https://user-images.githubusercontent.com/99068563/168751753-64bf5466-86eb-4fa5-ae4c-b7a256ada547.png">
